name: Unit Test

on:
    push:
      branches:
        - master
    pull_request:
      branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - name: Run Tests
        run: |
          yarn
          yarn test
